#4Ïßspi
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#############SPI Configurate Setting###################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

#sys_clk and rst
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN N15 [get_ports sys_rst_n]
set_property PACKAGE_PIN W19 [get_ports sys_clk]



set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam1_pclk_IBUF]


set_property IOSTANDARD LVCMOS33 [get_ports cam1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam1_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cam1_href]
set_property IOSTANDARD LVCMOS33 [get_ports cam1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports sccb1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports sccb1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports cam_rst_n]

set_property PACKAGE_PIN N14 [get_ports {cam1_data[0]}]
set_property PACKAGE_PIN N13 [get_ports {cam1_data[1]}]
set_property PACKAGE_PIN R19 [get_ports {cam1_data[2]}]
set_property PACKAGE_PIN P19 [get_ports {cam1_data[3]}]
set_property PACKAGE_PIN U22 [get_ports {cam1_data[4]}]
set_property PACKAGE_PIN AA20 [get_ports {cam1_data[5]}]
set_property PACKAGE_PIN R18 [get_ports {cam1_data[6]}]
set_property PACKAGE_PIN U21 [get_ports {cam1_data[7]}]
set_property PACKAGE_PIN R14 [get_ports sccb1_scl]
set_property PACKAGE_PIN P14 [get_ports sccb1_sda]
set_property PACKAGE_PIN T18 [get_ports cam1_vsync]
set_property PACKAGE_PIN T21 [get_ports cam1_href]
set_property PACKAGE_PIN AA21 [get_ports cam1_pclk]
set_property PACKAGE_PIN R17 [get_ports cam_pwdn]
set_property PACKAGE_PIN P16 [get_ports cam_rst_n]

#IIC
set_property IOSTANDARD LVCMOS33 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_sda]
set_property PACKAGE_PIN E19 [get_ports ddc_scl]
set_property PACKAGE_PIN D19 [get_ports ddc_sda]


#hdmi_out

set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_out_rgb[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_rst_n]
set_property PACKAGE_PIN K19 [get_ports hdmi_out_de]
set_property PACKAGE_PIN K17 [get_ports hdmi_out_hsync]
set_property PACKAGE_PIN J17 [get_ports hdmi_out_vsync]
set_property PACKAGE_PIN K18 [get_ports hdmi_out_clk]
set_property PACKAGE_PIN J16 [get_ports hdmi_out_rst_n]
set_property PACKAGE_PIN H13 [get_ports {hdmi_out_rgb[23]}]
set_property PACKAGE_PIN G13 [get_ports {hdmi_out_rgb[22]}]
set_property PACKAGE_PIN G15 [get_ports {hdmi_out_rgb[21]}]
set_property PACKAGE_PIN G16 [get_ports {hdmi_out_rgb[20]}]
set_property PACKAGE_PIN G17 [get_ports {hdmi_out_rgb[19]}]
set_property PACKAGE_PIN G18 [get_ports {hdmi_out_rgb[18]}]
set_property PACKAGE_PIN J14 [get_ports {hdmi_out_rgb[17]}]
set_property PACKAGE_PIN H14 [get_ports {hdmi_out_rgb[16]}]
set_property PACKAGE_PIN J15 [get_ports {hdmi_out_rgb[15]}]
set_property PACKAGE_PIN H15 [get_ports {hdmi_out_rgb[14]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_out_rgb[13]}]
set_property PACKAGE_PIN H18 [get_ports {hdmi_out_rgb[12]}]
set_property PACKAGE_PIN J19 [get_ports {hdmi_out_rgb[11]}]
set_property PACKAGE_PIN H19 [get_ports {hdmi_out_rgb[10]}]
set_property PACKAGE_PIN H20 [get_ports {hdmi_out_rgb[9]}]
set_property PACKAGE_PIN G20 [get_ports {hdmi_out_rgb[8]}]
set_property PACKAGE_PIN J20 [get_ports {hdmi_out_rgb[7]}]
set_property PACKAGE_PIN J21 [get_ports {hdmi_out_rgb[6]}]
set_property PACKAGE_PIN J22 [get_ports {hdmi_out_rgb[5]}]
set_property PACKAGE_PIN H22 [get_ports {hdmi_out_rgb[4]}]
set_property PACKAGE_PIN K13 [get_ports {hdmi_out_rgb[3]}]
set_property PACKAGE_PIN K14 [get_ports {hdmi_out_rgb[2]}]
set_property PACKAGE_PIN L16 [get_ports {hdmi_out_rgb[1]}]
set_property PACKAGE_PIN K16 [get_ports {hdmi_out_rgb[0]}]